### ISSUE TITLE
Avoid Raspberry Pi

### ISSUE THREAD

**Issue by ajl000** [alknopfler/alkalarm#12]
This is a great project 

I have been looking at a few things like GOBOT and Firmata but this aside, I was wondering whether a direct connection to a PC (say an intel nuc) could be made with a USB RF 433MHz transceiver such as https://www.ebay.com.au/itm/433Mhz-CC1101-USB-Wireless-RF-Transceiver-Module-10mW-USB-UART-RS232-MAX232-/293352781233.

Otherwise it seems that I would have to buy and wire a Raspberry PI.  I have also briefly looked at GOTIFY

Sorry if this is a dumb question and posted in the wrong place.  I have no idea how to interface a USB RF 433Mhz transceiver through USB

Adam

**Comment by alknopfler** [comment]
Look at this https://hackaday.com/2020/06/27/433-on-a-stick/
